list p=16F877A
INCLUDE <P16F877A.INC>
	SAYAC EQU 0X25
	ORG 0X00
	GOTO ANAPROGRAM
    ORG 0X04

KESME
	BTFSS INTCON,T0IF
	RETFIE
	BCF INTCON,T0IF
	DECFSZ SAYAC,1
	RETFIE
LED_YAKMA
	MOVLW 0X01
	XORWF PORTB,1
	MOVLW D'250'
	MOVWF SAYAC
	RETFIE
ANAPROGRAM
	MOVLW D'250'
	MOVWF SAYAC
	BSF STATUS,RP0
	CLRF TRISB
	BANKSEL TMR0
	MOVLW D'6'     ;timer 0 baþlangýç deðeri
	MOVWF TMR0
	BANKSEL OPTION_REG
	MOVLW B'00000011' ; PRESCALER 16 AYARLANDI
	MOVWF OPTION_REG
	BANKSEL INTCON
	MOVLW B'11100000' ;kesmeler aktifleþtirildi.
	MOVWF INTCON
dongu
	goto dongu	
END	