# MPLAB IDE generated this makefile for use with GNU make.
# Project: deneme.mcp
# Date: Fri Nov 18 20:01:58 2011

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Untitled.cof : Untitled.o
	$(CC) /p16F877A "Untitled.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Untitled.cof" /M"Untitled.map" /W /x

Untitled.o : Untitled.asm C:/Program\ Files/Microchip/MPASM\ Suite/P16F877A.inc
	$(AS) /q /p16F877A "Untitled.asm" /l"Untitled.lst" /e"Untitled.err" /d__DEBUG=1

clean : 
	$(CC) "Untitled.o" "Untitled.hex" "Untitled.err" "Untitled.lst" "Untitled.cof"

