# MPLAB IDE generated this makefile for use with GNU make.
# Project: deneme1.mcp
# Date: Wed Sep 26 10:38:36 2012

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

deneme1.cof : deneme1.o
	$(CC) /p16F877 "deneme1.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"deneme1.cof" /M"deneme1.map" /W

deneme1.o : deneme1.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/p16f877.inc
	$(AS) /q /p16F877 "deneme1.asm" /l"deneme1.lst" /e"deneme1.err" /o"deneme1.o" /d__DEBUG=1

clean : 
	$(CC) "deneme1.o" "deneme1.err" "deneme1.lst" "deneme1.cof" "deneme1.hex"

